### ISSUE TITLE
Solder mask

### ISSUE THREAD

**Issue by mannahusum** [4pplet/BLE-Test#1]
I really appreciate your work. I’m on my way to build a keyboard, my first, with your design.

PCBway complained about drilling away a via, if I get it right:

As shown in attached screenshots, the soldermask opening on the GTS layer is larger than pads on the GTL layer. But some of the soldermask opening on the GBS layer is smaller than pads on the GBL layer, so could you enlarge the soldermask opening 2mil around these pads like the soldermask opening on the GTS layer?

![Soldermask_1](https://user-images.githubusercontent.com/223651/123741249-fcf63a80-d8a9-11eb-8f7e-b1d3dde19449.png)
![Soldermask_2](https://user-images.githubusercontent.com/223651/123741261-01baee80-d8aa-11eb-805a-e477a4a534bd.png)

I don’t have the software to create and offer a fix, though

**Comment by 4pplet** [comment]
Hi!

Thanks for showing interest in the project! Sorry for the delayed response. 

I'll see if I can sort it out. If I get this right, they are concerned about that the soldermask covers the pad on one side if the PCB? It is done like this on purpose, so that the pad is not visible on the side you place the switches. It is not an issue. :)

What via are they complaining about?

Will you be doing a full assembly of the boards, with module and everything from PCBway?

Also, are you aware that you will need to flash bootloader? The module does not ship with the UF2 bootloader.
